import React, { useState, useEffect } from 'react';
import { Line } from 'react-chartjs-2';
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend,
} from 'chart.js';
import axios from 'axios';
import './AnalyticsDashboard.css';

ChartJS.register(
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Title,
    Tooltip,
    Legend
);

interface ChartData {
    labels: string[];
    datasets: {
        label: string;
        data: number[];
        borderColor: string;
        backgroundColor: string;
    }[];
}

const AnalyticsDashboard: React.FC = () => {
    const [chartData, setChartData] = useState<ChartData | null>(null);
    const [message, setMessage] = useState('');
    const token = localStorage.getItem('token');

    useEffect(() => {
        if (token) {
            fetchAnalyticsData();
        }
    }, [token]);

    const fetchAnalyticsData = async () => {
        try {
            // This is a mock API call. In a real scenario, you would fetch processed data
            // from your backend, which would have been generated by the Python service.
            const response = await axios.get('/api/analytics/mock-data', {
                headers: { Authorization: `Bearer ${token}` }
            });
            setChartData(response.data);
        } catch (error: any) {
            setMessage(error.response?.data || 'Failed to fetch analytics data.');
        }
    };

    const options = {
        responsive: true,
        plugins: {
            legend: {
                position: 'top' as const,
            },
            title: {
                display: true,
                text: 'Sample Analytics Data',
            },
        },
    };

    return (
        <div className="analytics-dashboard-container">
            <h2>Analytics Dashboard</h2>
            {message && <p>{message}</p>}
            {chartData ? (
                <div className="chart-container">
                    <Line options={options} data={chartData} />
                </div>
            ) : (
                <p>Loading analytics data or no data available...</p>
            )}
        </div>
    );
};

export default AnalyticsDashboard;